spring:
  application:
    name: Client2
  security:
    user:
      name: Junior
      password: 123456
      roles: ADMIN
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8081

basicURL: http://localhost:8080

